# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Install SFDX CLI and Scanner
      run: |
        npm install sfdx-cli
        npx sfdx plugins:install @salesforce/sfdx-scanner
    - name: SFDX Scanner
      uses: mattisdada/sfdx-scan-pull-request@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit_sha: ${{ github.event.pull_request.head.sha }}
        report-mode: check-runs
        severity-threshold: 1